### ISSUE TITLE
Save selected type of cards for the next session

### ISSUE THREAD

**Issue by franpog859** [caioedut/scrumplanning#1]
Hi! I'd like to create a pull request with a feature that will save the selected type of cards from the previous session and set it in the new one. 
Isn't it already done [here (setting)](https://github.com/caioedut/scrumplanning/blob/cd7750a551f55577a12289839b2342cd2e67129d/www/page/cards/cards.js#L9) and [here (saving)](https://github.com/caioedut/scrumplanning/blob/cd7750a551f55577a12289839b2342cd2e67129d/www/page/cards/cards.js#L61)? I haven't compiled it yet, just asking 😄

**Comment by caioedut** [comment]
Here are:

https://github.com/caioedut/scrumplanning/blob/master/www/page/cards/cards.js#L9
https://github.com/caioedut/scrumplanning/blob/master/www/page/cards/cards.js#L61
https://github.com/caioedut/scrumplanning/blob/master/www/js/config/appCfg.js#L42

For now in beta version on Play Store.
Is that what you talking about?

**Comment by franpog859** [comment]
Lovely! It works as I wanted it to 😄 I think pull request is not needed anymore.

**Comment by caioedut** [comment]
Thank u :)
